---
- name: Configure Cisco IOS XE devices
  hosts: iosxe
  gather_facts: no

  tasks:

    - name: Configure ACL
      cisco.ios.ios_config:
        lines:
          - 10 permit ip host 1.1.1.1 any log
          - 20 permit ip host 2.2.2.2 any log
        parents: ip access-list extended AnsibleTest
        before: no ip access-list extended AnsibleTest
        match: exact
