---
- name: Manage Cisco IOS XE device
  hosts: ios_xe_devices
  gather_facts: no
  connection: network_cli

  tasks:

    - name: Set hostname
      cisco.ios.ios_config:
        lines:
          - hostname Router-01

    - name: Configure interface GigabitEthernet1
      cisco.ios.ios_config:
        lines:
          - description Uplink to ISP
          - ip address 192.0.2.10 255.255.255.0
          - no shutdown
        parents: interface GigabitEthernet1
